<?xml version="1.0" encoding="utf-8"?><Database Name="MyWord" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MyWord;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="myword.DAL.Properties.Settings" SettingsPropertyName="MyWordConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_Table" Member="user_Table">
    <Type Name="user_Table">
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>