#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myword.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyWord")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertuser_Table(user_Table instance);
    partial void Updateuser_Table(user_Table instance);
    partial void Deleteuser_Table(user_Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::myword.DAL.Properties.Settings.Default.MyWordConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user_Table> user_Table
		{
			get
			{
				return this.GetTable<user_Table>();
			}
		}
		
		public System.Data.Linq.Table<wordpre> wordpre
		{
			get
			{
				return this.GetTable<wordpre>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_Table")]
	public partial class user_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Userid;
		
		private string _Name;
		
		private string _Password;
		
		private string _Email;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUseridChanging(int value);
    partial void OnUseridChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public user_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Userid
		{
			get
			{
				return this._Userid;
			}
			set
			{
				if ((this._Userid != value))
				{
					this.OnUseridChanging(value);
					this.SendPropertyChanging();
					this._Userid = value;
					this.SendPropertyChanged("Userid");
					this.OnUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wordpre")]
	public partial class wordpre
	{
		
		private System.Nullable<int> _id;
		
		private string _type;
		
		private string _type1;
		
		private string _type2;
		
		private string _type3;
		
		private string _type4;
		
		private string _word;
		
		private string _wordlevel;
		
		private string _rootvariant;
		
		private string _meaning;
		
		private string _soundmark;
		
		private string _structure;
		
		private string _explain;
		
		private string _translation;
		
		private string _example;
		
		private string _exampletranslation;
		
		public wordpre()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type1", DbType="NVarChar(255)")]
		public string type1
		{
			get
			{
				return this._type1;
			}
			set
			{
				if ((this._type1 != value))
				{
					this._type1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type2", DbType="NVarChar(255)")]
		public string type2
		{
			get
			{
				return this._type2;
			}
			set
			{
				if ((this._type2 != value))
				{
					this._type2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type3", DbType="NVarChar(255)")]
		public string type3
		{
			get
			{
				return this._type3;
			}
			set
			{
				if ((this._type3 != value))
				{
					this._type3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type4", DbType="NVarChar(255)")]
		public string type4
		{
			get
			{
				return this._type4;
			}
			set
			{
				if ((this._type4 != value))
				{
					this._type4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_word", DbType="NVarChar(255)")]
		public string word
		{
			get
			{
				return this._word;
			}
			set
			{
				if ((this._word != value))
				{
					this._word = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wordlevel", DbType="NVarChar(255)")]
		public string wordlevel
		{
			get
			{
				return this._wordlevel;
			}
			set
			{
				if ((this._wordlevel != value))
				{
					this._wordlevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rootvariant", DbType="NVarChar(255)")]
		public string rootvariant
		{
			get
			{
				return this._rootvariant;
			}
			set
			{
				if ((this._rootvariant != value))
				{
					this._rootvariant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meaning", DbType="NVarChar(255)")]
		public string meaning
		{
			get
			{
				return this._meaning;
			}
			set
			{
				if ((this._meaning != value))
				{
					this._meaning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soundmark", DbType="NVarChar(255)")]
		public string soundmark
		{
			get
			{
				return this._soundmark;
			}
			set
			{
				if ((this._soundmark != value))
				{
					this._soundmark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_structure", DbType="NVarChar(255)")]
		public string structure
		{
			get
			{
				return this._structure;
			}
			set
			{
				if ((this._structure != value))
				{
					this._structure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_explain", DbType="NVarChar(255)")]
		public string explain
		{
			get
			{
				return this._explain;
			}
			set
			{
				if ((this._explain != value))
				{
					this._explain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_translation", DbType="NVarChar(255)")]
		public string translation
		{
			get
			{
				return this._translation;
			}
			set
			{
				if ((this._translation != value))
				{
					this._translation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_example", DbType="NVarChar(255)")]
		public string example
		{
			get
			{
				return this._example;
			}
			set
			{
				if ((this._example != value))
				{
					this._example = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exampletranslation", DbType="NVarChar(255)")]
		public string exampletranslation
		{
			get
			{
				return this._exampletranslation;
			}
			set
			{
				if ((this._exampletranslation != value))
				{
					this._exampletranslation = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
